### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DanielDomingueti** [DanielDomingueti/twitter-bot-bitcoin#6]
## FIX percentage change
- [x] if both are positive
- [x] if both are negative
- [x] if 1h positive and 24h negative
---

## Think about a way to scale it up (multiple requests a day)
- [x] Change archtecture
- [x] Changed x % in y hours.
---

## Improve tweet response
- [x] Format Double with two decimal cases
- [x] Include data [Jul 22] - 13:48:09 UTC
- [x] Include emojis 
- [x] If statment (>0 GREEN, else RED) for %% change
---

## Refactoring
- [x] arrange packages
- [x] remove crypto package. Keep only CryptoData
---

## Design
- [x] Create a description
- [x] Create pictures
---

## Create CRON
- [x] Execute it X times a day.
---

## ToDo before deploy
- [x] remove everything related to database connections
- [x] fix utc time
- [x] generate .jar
- [x] insert pem file into .jar directory.
- [x] ssh -i "home/Downloads/aws-twitter-bot.pem" target/twitter-bot.jar ubuntu@ec2-3-83-141-99.compute-1.amazonaws.com

## Kubernetes cluster
- [x] Implementation or oracle machine (have to decide which one)

## Exception handling
   - [ ] BadRequestException
   - [ ] Timestamp
